name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Inject TBA key
        run: |
          echo "Secret length: ${#TBA_KEY}"
          echo "Before:"
          grep -o 'TBA_KEY.*' index.html | head -1
          sed -i "s|__TBA_KEY_PLACEHOLDER__|${TBA_KEY}|g" index.html
          echo "After:"
          grep -o 'TBA_KEY.*' index.html | head -1
           env:
            TBA_KEY: k3RQ7yVrZdKqUt6RjDlOKYadDOglo2B41X1CE6Fv5eUozinzBfDhr2aw3hg5D22z
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
